### ISSUE TITLE
Pandas incompatibility to_msgpack

### ISSUE THREAD

**Issue by Zeik0s** [arunpersaud/gopro-rescue#1]
I'm trying to recover a broken microsd where the filesystem was corrupted due to a disconnect of the usb port. I noticed, that the creation of the dataframe with `gopro-rescue create_df` is broken due to the deprecation of `to_msgpack` in pandas >1.0.0. 

Do you have an idea how this can be worked around?

**Comment by arunpersaud** [comment]
It's been a while that I looked at this... I think the to_msgpack and read_msgpack is just one way to save the pandas dataframe that stores all kind of information of the process. You could just change all those calls to any other method to safe a dataframe, for example to_parquet and read_parquet.

**Comment by Zeik0s** [comment]
Nice, looks like this works. Will report my progress, if that's ok. 😀

**Comment by arunpersaud** [comment]
Sure... hope this works for you... I managed to get most of my videos back, but it's been a long time ago and I'm not sure how much hand editing and manipulating is needed to use these scripts anymore.   Good luck!

**Comment by Zeik0s** [comment]
Unfortunately didn't get it to work, but i managed to get the pictures off the card by another way.
